In [1]:
pwd


'C:\\Users\\Asus'

In [12]:
import random
lst=random.sample(range(1,30), 20)
lst.sort()

[10, 22, 16, 7, 1, 2, 18, 14, 29, 8, 12, 15, 19, 9, 20, 28, 3, 23, 27, 17]

In [2]:
cd C:\\Users\\User\\Desktop\\violence_detection

[WinError 3] The system cannot find the path specified: 'C:\\\\Users\\\\User\\\\Desktop\\\\violence_detection'
C:\Users\Asus


In [54]:
import math
import numpy as np
from PIL import Image
import os
import random
com_list=[]
res=[]
file_list=[]

ss='C:\\Users\\User\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
os.chdir(ss)


file_list = os.listdir(ss) 
number_of_files = len(file_list)
print(str(z) + " --- "+str(number_of_files))
lst=random.sample(range(1,number_of_files), 11)
lst.sort()
for x in lst:
    print(x)

50 --- 49
3
4
7
25
27
32
36
38
39
41
45


In [59]:
import math
import numpy as np
from PIL import Image
import os
kk=[]
for z in range(1,101):
    com_list=[]
    res=[]
    ss='C:\\Users\\User\\Desktop\\violence_detection\\f\\data_'+str(z)
    os.chdir(ss)
    file_list = os.listdir(ss) 
    number_of_files = len(file_list)
#print(str(z) + " --- "+str(number_of_files))
    lst=random.sample(range(1,number_of_files), 11)
    lst.sort()
    
    for x in lst:
           # print(x)

            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1  
        X.append(res)
        y.append(0)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 37)

In [57]:
lst


[2, 14, 20, 23, 24, 26, 30, 32, 33, 37, 41]

In [58]:
X=[]
y=[]

In [4]:
import math
import numpy as np
from PIL import Image
import os

for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\fight\\data_'+str(z)
        os.chdir(ss)


        for x in range(42):
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

        X.append(res)
        y.append(1)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [12]:
import numpy as np
a = np.array(X)
len(a.shape)

In [5]:
len(X)
len(y)

84

In [6]:
import math
import numpy as np
from PIL import Image
import os

for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)


        for x in range(42):
           # print(x)

            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1  
        X.append(res)
        y.append(0)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


import matplotlib.pyplot as plt
from sklearn import svm

clf = svm.SVC(gamma=0.001, C=100)
clf.fit(X,y)



In [57]:
len(X)

126

In [58]:
len(y)

126

In [36]:
com_list=[]
res=[]
ss='C:\\Users\\User\\Desktop\\violence_detection\\nf\\ndata_98'
os.chdir(ss)    
    
for x in range(42):
    print(x)
    
    s='frame'+str(x)+'.jpg'
    #print(s)
    im = Image.open(s, 'r')
    rgb_list= list(im.getdata())
    i=0
    if x == 0:
        i=0
        for (a,b,c) in rgb_list:
            com_list.insert(i,math.sqrt(a*a+b*b+c*c))
            i=i+1   
    else:
        i=0
        for (a,b,c) in rgb_list:
            cm=math.sqrt(a*a+b*b+c*c)
            res.append(abs(com_list[i]-cm))
            com_list[i]=cm
            i=i+1 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41


In [7]:
import random
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]

In [8]:
from sklearn import svm
clf = svm.SVC(gamma='auto')
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
y

[0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0]

In [69]:
import math
import numpy as np
from PIL import Image
import os
kk=[]
for z in range(1,101):
    com_list=[]
    res=[]
    ss='C:\\Users\\User\\Desktop\\violence_detection\\f\\data_'+str(z)
    os.chdir(ss)
    
    
    for x in range(42):
        print(x)
        s='frame'+str(x)+'.jpg'
        #print(s)
        im = Image.open(s, 'r')
        rgb_list= list(im.getdata())
        i=0
        if x == 0:
            i=0
            for (a,b,c) in rgb_list:
                com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                i=i+1   
        else:
            i=0
            for (a,b,c) in rgb_list:
                cm=math.sqrt(a*a+b*b+c*c)
                res.append(abs(com_list[i]-cm))
                com_list[i]=cm
                i=i+1 
                
    kk.append(clf.predict([res]))
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
2

28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
1

In [73]:
kk

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [71]:
import math
import numpy as np
from PIL import Image
import os
kk=[]
for z in range(1,101):
    com_list=[]
    res=[]
    ss='C:\\Users\\User\\Desktop\\violence_detection\\nf\\ndata_'+str(z)
    os.chdir(ss)
    
    
    for x in range(42):
        print(x)
        s='frame'+str(x)+'.jpg'
        #print(s)
        im = Image.open(s, 'r')
        rgb_list= list(im.getdata())
        i=0
        if x == 0:
            i=0
            for (a,b,c) in rgb_list:
                com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                i=i+1   
        else:
            i=0
            for (a,b,c) in rgb_list:
                cm=math.sqrt(a*a+b*b+c*c)
                res.append(abs(com_list[i]-cm))
                com_list[i]=cm
                i=i+1 
                
    kk.append(clf.predict([res]))
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
2

29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
0
1
2
3
4
5
6
7
8
9
10
11
12
13
1

In [65]:
len(X)

144

In [ ]:
import math
import numpy as np
from PIL import Image
import os
import random
X=[]
y=[]
for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\FFF\\data_'+str(z)
        os.chdir(ss)


        for x in range(42):
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

        X.append(res)
        y.append(1)

for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\NFFF\\ndata_'+str(z)
        os.chdir(ss)


        for x in range(42):
            #print(x)

            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1  
        X.append(res)
        y.append(0)
        

c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]

from sklearn import svm
clf = svm.SVC(gamma='auto')
clf.fit(X, y) 

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37


In [9]:
import math
import numpy as np
from PIL import Image
import os
test_x=[]
test_y=[]
for z in range(1,101):
    print(z)
    if z%6==0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\fight\\data_'+str(z)
        os.chdir(ss)


        for x in range(42):
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

        test_x.append(res)
        test_y.append(1)
for z in range(1,101):
    print(z)
    if z%6==0:
        com_list=[]
        res=[]
        ss='C:\\Users\\User\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)


        for x in range(42):
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

        test_x.append(res)
        test_y.append(0)

import random
c =list( zip(test_x,test_y))
random.shuffle(c)
test_x = [i[0] for i in c]
test_y = [i[1] for i in c]

kk=[]
for z in range(1,len(test_x)):
    kk.append(clf.predict([test_x[z]]))
    
ac=0
tt=0
for z in range(0,len(kk)):
     if kk[z][0]==test_y[z+1]:
        ac=ac+1
tt=ac/len(kk)*100    
print(tt)

print("Accuracy of the system is : " + str(tt) +"%")

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
51.61290322580645
Accuracy of the system is : 51.61290322580645%


In [66]:
import math
import numpy as np
from PIL import Image
import os
import random
kk=[]
X=[]
y=[]
for z in range(1,101):
    com_list=[]
    res=[]
    ss='C:\\Users\\User\\Desktop\\violence_detection\\fight\\data_'+str(z)
    os.chdir(ss)
    file_list = os.listdir(ss) 
    number_of_files = len(file_list)
#print(str(z) + " --- "+str(number_of_files))
    lst=random.sample(range(1,number_of_files), 11)
    lst.sort()
    
    for x in lst:
           # print(x)

            s='frame'+str(x)+'.jpg'
            print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1  
            X.append(res)
            y.append(0)

frame1.jpg


TypeError: 'list' object is not callable

In [64]:
import math
import numpy as np
from PIL import Image
import os
import random
X=[]
y=[]
for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        
        ss='C:\\Users\\User\\Desktop\\violence_detection\\fight\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

                X.append(res)
                y.append(1)
for z in range(1,101):
    print(z)
    if z%6!=0:
        com_list=[]
        
        ss='C:\\Users\\User\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

                X.append(res)
                y.append(0)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [65]:
len(X)

7964

In [66]:
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]

from sklearn import svm
clf = svm.SVC(gamma='auto')
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [72]:
import math
import numpy as np
from PIL import Image
import os
import random
kk=[]
for z in range(1,101):
    #print("------"+str(z))
    #print(z)
    if z%6==0:
        print("------"+str(z))
        com_list=[]
        cnt=0
        ss='C:\\Users\\User\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 30)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            rgb_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for (a,b,c) in rgb_list:
                    com_list.insert(i,math.sqrt(a*a+b*b+c*c))
                    i=i+1   
            else:
                i=0
                for (a,b,c) in rgb_list:
                    cm=math.sqrt(a*a+b*b+c*c)
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

                
                rs=clf.predict([res])
                if rs[0]==1:
                    cnt=cnt+1;
                    #print(cnt)
        print(cnt)
        if cnt>(number_of_files/2):
            print("fight")
                


    

------6
48
fight
------12
48
fight
------18
48
fight
------24
48
fight
------30
48
fight
------36
29
fight
------42
32
fight
------48
48
fight
------54
34
fight
------60
0
------66
18
------72
48
fight
------78
48
fight
------84
48
fight
------90
48
fight
------96
48
fight


In [41]:
kk

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([0]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),

In [60]:
len(X)

5040

In [2]:
import cv2

winSize = (200,100)
blockSize = (40,20)
blockStride = (20,10)
cellSize = (20,10)
nbins = 9
derivAperture = 1
winSigma = -1.
histogramNormType = 0
L2HysThreshold = 0.2
gammaCorrection = 1
nlevels = 64
signedGradients = True
 
hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

In [ ]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
X=[]
y=[]
for z in range(1,31):
    print(z)
    if z%6!=0:
        com_list=[]
        
        ss='C:\\Users\\User\\Desktop\\violence_detection\\ff\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            
            
            hog = cv2.HOGDescriptor()
            im = cv2.imread(s)
            h = hog.compute(im).ravel()
            
            
            
            hog_list= h.tolist()
            i=0
            if x == 0:
                i=0
                for a in hog_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                for b in hog_list:
                    cm=b
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 

                X.append(res)
                y.append(1)
