In [1]:
cd C:\\Users\\ASUS\\Desktop\\violence_detection

C:\Users\ASUS\Desktop\violence_detection


In [2]:
import cv2
import numpy as np
import os
import math
import numpy as np
from PIL import Image
width = 128
height =64
dim = (width, height)

for frm_no in range(1,101):
    dr='./movie fight/Peliculas/noFights/'+str(frm_no)+'.mpg'
    cap = cv2.VideoCapture(dr)
    fl='ndata_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

for frm_no in range(1,101):
    dr='./movie fight/Peliculas/fights/newfi'+str(frm_no)+'.avi'
    cap = cv2.VideoCapture(dr)
    fl='data_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

In [30]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
X=[]
y=[]
for z in range(1,101):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\bin_fight\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,2):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
          
            #print(s)
            #print(number_of_files)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            print(hog_lst)
            name = 'C:\\Users\\Asus\\Desktop\\violence_detection\\' + str(x) + 'f.jpg'
            img = Image.new( 'L', (128,64), "black")
            pixels = img.load()
            k=0
            for j in range(img.size[1]):
                for i in range(img.size[0]):
                    pixels[i,j] =hog_lst[k]
                    k=k+1
                
            
            img.save(name)
            X.append(hog_lst)
            y.append(1)
for z in range(1,2):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\bin_nfight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files):
            res=[]
            print(number_of_files)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            hog_lst[0].shape
            name = 'C:\\Users\\Asus\\Desktop\\violence_detection\\' + str(x) + 'n.jpg'
            #cv2.destroyAllWindows()
            img = Image.new( 'L', (128,64), "black")
            pixels = img.load()
            k=0
            for j in range(img.size[1]):
                for i in range(img.size[0]):
                    pixels[i,j] =hog_lst[k]
                    k=k+1
                
            
            img.save(name)
            cv2.destroyAllWindows()
            X.append(hog_lst)
            y.append(0)



1
[0.18784917891025543, 0.21633656322956085, 0.21408717334270477, 0.008837148547172546, 0.21749503910541534, 0.1519235223531723, 0.2014111876487732, 0.0668591782450676, 0.0707097128033638, 0.11302553117275238, 0.10490866750478745, 0.08598116785287857, 0.006876936182379723, 0.1624687761068344, 0.10778583586215973, 0.22008097171783447, 0.09297385811805725, 0.07483235746622086, 0.22008097171783447, 0.18920782208442688, 0.22008097171783447, 0.12627428770065308, 0.19113518297672272, 0.1980004757642746, 0.0944463387131691, 0.12541504204273224, 0.22008097171783447, 0.22008097171783447, 0.22008097171783447, 0.08886571228504181, 0.040138859301805496, 0.20801033079624176, 0.21263107657432556, 0.18985335528850555, 0.2017110139131546, 0.22008097171783447, 0.030132940039038658, 0.12138881534337997, 0.29021456837654114, 0.003498815931379795, 0.03446167707443237, 0.013784045353531837, 0.13050371408462524, 0.05915531516075134, 0.03714193031191826, 0.05754425376653671, 0.19736063480377197, 0.2902145683

SystemError: new style getargs format but argument is not a tuple

In [3]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
acc=0
tot=0
for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            acc=acc+1
            print("fight")
        else:
            print("non fight")

            

for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            print("fight")
        else:
            acc=acc+1
            print("non fight")

acuracy=(acc/tot)*100
print(acuracy)

1
2
3
4
5


AttributeError: 'int' object has no attribute 'predict'

In [12]:
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]



In [ ]:
from tkinter import *
from tkinter import filedialog
import math
import numpy as np
from PIL import Image
from sklearn import svm
import os
import random
import cv2
root = Tk()
X=[]
y=[]
clf=0
print('Videos are processing!')
for z in range(1,101):
    #print(z)
    if z%3!=0:
            #com_list=[]

        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)

        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
            #print(str(z) + " --- "+str(number_of_files))
            #lst=random.sample(range(1,number_of_files), 31)
            #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
                #print(x)
            s='frame'+str(x)+'.jpg'
                #print(s)
            gray=cv2.imread(s)

            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True

            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            X.append(hog_lst)
            y.append(1)
for z in range(1,101):
    #print(z)
    if z%3!=0:
            #com_list=[]

        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)

        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
            #print(str(z) + " --- "+str(number_of_files))
            #lst=random.sample(range(1,number_of_files), 31)
            #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
                #print(x)
            s='frame'+str(x)+'.jpg'
                #print(s)
            gray=cv2.imread(s)

            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True

            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            X.append(hog_lst)
            y.append(0)
print('Videos are processed!')
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]
print('Training the model')
    
clf = svm.SVC(gamma='auto')
clf.fit(X, y)

print('Model training finished')

             
def onclick3(self):
    print("Video Number...............Expected result.........Experimental result")
    tmp1 = str(eval(inp1.get()))
    tmp2 = str(eval(inp2.get()))
    fr = int(tmp1)
    to = int(tmp2)
    acc=0
    tot=0
    for z in range(fr,to):
        #print(z)
        if z%5==0:
            tot=tot+1
            #com_list=[]

            ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
            os.chdir(ss)

            file_list = os.listdir(ss) 
            number_of_files = len(file_list)
            #print(str(z) + " --- "+str(number_of_files))
            #lst=random.sample(range(1,number_of_files), 31)
            #lst.sort()

            cnt=0
            for x in range(1,number_of_files+1):
                res=[]
                #print(x)
                s='frame'+str(x)+'.jpg'
                #print(s)
                gray=cv2.imread(s)

                cell_size=(8,8)
                block_size=(2,2)
                nbins=9


                winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
                blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
                blockStride = (cell_size[1], cell_size[0])
                cellSize = (cell_size[1], cell_size[0])
                nbins = 9
                derivAperture = 1
                winSigma = -1.
                histogramNormType = 0
                L2HysThreshold = 0.2
                gammaCorrection = 1
                nlevels = 64
                signedGradients = True

                hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

                n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
                hog_feats = hog.compute(gray).ravel()
                hog_lst=hog_feats.tolist()
                rs=clf.predict([hog_lst])

                if rs[0]==1:
                    cnt=cnt+1;
                        #print(cnt)
            #print(cnt)
            
            if cnt>(number_of_files/2):
                acc=acc+1
                print(str(z)+".........................fight....................."+"fight")
                
            else:
                print(str(z)+".........................fight....................."+"non fight")



    for z in range(fr,to):
        #print(z)
        if z%5==0:
            tot=tot+1
            #com_list=[]

            ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
            os.chdir(ss)

            file_list = os.listdir(ss) 
            number_of_files = len(file_list)
            #print(str(z) + " --- "+str(number_of_files))
            #lst=random.sample(range(1,number_of_files), 31)
            #lst.sort()

            cnt=0
            for x in range(1,number_of_files+1):
                res=[]
                #print(x)
                s='frame'+str(x)+'.jpg'
                #print(s)
                gray=cv2.imread(s)

                cell_size=(8,8)
                block_size=(2,2)
                nbins=9


                winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
                blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
                blockStride = (cell_size[1], cell_size[0])
                cellSize = (cell_size[1], cell_size[0])
                nbins = 9
                derivAperture = 1
                winSigma = -1.
                histogramNormType = 0
                L2HysThreshold = 0.2
                gammaCorrection = 1
                nlevels = 64
                signedGradients = True

                hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

                n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
                hog_feats = hog.compute(gray).ravel()
                hog_lst=hog_feats.tolist()
                rs=clf.predict([hog_lst])
                if rs[0]==1:
                    cnt=cnt+1;
                        #print(cnt)
            #print(cnt)
            if cnt>(number_of_files/2):
                print(str(z)+".........................non fight................."+"fight")
            else:
                acc=acc+1
                print(str(z)+".........................non fight................."+"non fight")

    acuracy=(acc/tot)*100
   
    print("Accuracy: "+str(acuracy)+" %")
    tmp3 = str(acuracy) + " %"
    lvl10.configure(text=tmp3)
    #print(acuracy)
    #finalllll


root.geometry("600x500")
root.configure(bg='#151313')

topFrame = Frame(root)
topFrame.configure(bg='#151313')

lvl55 = Label(root, text="Training Completed")
lvl55.pack(pady=5)


topFrame.pack(pady=20)


lvl6 = Label(root, text="Input video range")
lvl6.pack(pady=5)

bottomFrame = Frame(root)


table2 = LabelFrame(bottomFrame)

lvl7 = Label(table2, text="Form")
lvl8 = Label(table2, text="TO")
inp1 = Entry(table2)
inp2 = Entry(table2)

lvl7.grid(row=0, sticky=W)
lvl8.grid(row=1, sticky=W)
inp1.grid(row=0, column=1)
inp2.grid(row=1, column=1)
table2.pack(pady=5)

btn2 = Button(bottomFrame, text="Run", bg='#070334', fg="white", padx=30)
btn2.bind("<Button-1>", onclick3)
btn2.pack(pady=5)
table3 = Frame(bottomFrame)
lvl9 = Label(table3, text="Accuracy")
lvl10 = Label(table3, text="----------")

lvl9.grid(row=0, sticky=W)
lvl10.grid(row=0, column=1)
table3.pack(pady=5)
bottomFrame.configure(bg='#151313')
bottomFrame.pack(pady=5)

root.mainloop()


Videos are processing!
Videos are processed!
Training the model
Model training finished
Video Number...............Expected result.........Experimental result
5.........................fight.....................fight
10.........................fight.....................fight
15.........................fight.....................fight
20.........................fight.....................fight
25.........................fight.....................fight
30.........................fight.....................fight
35.........................fight.....................fight
40.........................fight.....................fight
45.........................fight.....................fight
50.........................fight.....................fight
55.........................fight.....................fight
60.........................fight.....................fight
65.........................fight.....................fight
70.........................fight.....................fight
75..............

In [13]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(gamma='auto',kernel='linear')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 0
Accuracy: 1.00


1.0

In [15]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='rbf')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 51
Accuracy: 0.98
[[1389   51]
 [   0 1408]]


0.9648139146379018

In [16]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='poly')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1408
Accuracy: 0.51
[[1440    0]
 [1408    0]]


C:\Users\Asus\Anaconda3\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:538: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


0.0

In [17]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='sigmoid')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 63
Accuracy: 0.98
[[1377   63]
 [   0 1408]]


0.9567108848545544

In [18]:
from sklearn.linear_model import LogisticRegression

ppn = LogisticRegression(random_state=1)
ppn = ppn.fit(X_train1, y_train)
y_pred = ppn.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1
Accuracy: 1.00
[[1439    1]
 [   0 1408]]


0.9992979161446027

In [19]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1
Accuracy: 1.00
[[1439    1]
 [   0 1408]]


0.9992979161446027

In [20]:
import sklearn
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
clf = LDA()
clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 0
Accuracy: 1.00
[[1440    0]
 [   0 1408]]


1.0

In [21]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 83
Accuracy: 0.97


0.9433463718201924

In [22]:
from sklearn.neural_network import MLPClassifier
gnb = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(13, 2), random_state=1)
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 2
Accuracy: 1.00
[[1440    0]
 [   2 1406]]


0.9985962913108558

In [23]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
y_pred = neigh.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 0
Accuracy: 1.00
[[1440    0]
 [   0 1408]]


1.0