In [2]:
cd C:\\Users\\ASUS\\Desktop\\violence_detection

C:\Users\ASUS\Desktop\violence_detection


In [5]:
import cv2
import numpy as np
import os
import math
import numpy as np
from PIL import Image
width = 128
height =64
dim = (width, height)

for frm_no in range(1,501):
    dr='C:/Users/Asus/Desktop/violence_detection/hocky_fight/'+'fi'+str(frm_no)+'_xvid.avi'
    print(dr)
    cap = cv2.VideoCapture(dr)
    fl='data_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

for frm_no in range(1,501):
    dr='C:/Users/Asus/Desktop/violence_detection/hocky_fight/'+'fi'+str(frm_no)+'_xvid.avi'
    cap = cv2.VideoCapture(dr)
    fl='ndata_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()


C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi1_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi2_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi3_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi4_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi5_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi6_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi7_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi8_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi9_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi10_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi11_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi12_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi13_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi14_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi15_xvid.avi
C:/U

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi124_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi125_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi126_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi127_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi128_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi129_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi130_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi131_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi132_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi133_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi134_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi135_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi136_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi137_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_f

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi245_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi246_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi247_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi248_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi249_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi250_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi251_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi252_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi253_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi254_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi255_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi256_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi257_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi258_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_f

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi366_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi367_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi368_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi369_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi370_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi371_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi372_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi373_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi374_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi375_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi376_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi377_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi378_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi379_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_f

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi487_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi488_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi489_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi490_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi491_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi492_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi493_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi494_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi495_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi496_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi497_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi498_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi499_xvid.avi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi500_xvid.avi


In [2]:
import math
import numpy as np
from PIL import Image
import os
import random
for z in range(1,501):
    print(z)
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\fight\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
        



        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                t=0
                p_n=0;
                for a in gray_list: 
                    cm=a
                    t=t+abs(com_list[i]-cm)
                    p_n=p_n+1;
                    
                if t/p_n>256*0.4:
                    for a in gray_list:
                        cm=a
                        res.append(abs(com_list[i]-cm))
                        com_list[i]=cm
                        i=i+1 

                        img = Image.new( 'L', (128,64), "black")
                        pixels = img.load()
                        k=0
                        for j in range(img.size[1]):
                            for i in range(img.size[0]):
                                pixels[i,j] =res[k]
                                k=k+1

                        name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\bin_f\\data_'+str(z)+'\\'+str(s) 
                        img.save(name)

                
for z in range(1,501):
    print(z)
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                t=0
                p_n=0;
                for a in gray_list: 
                    cm=a
                    t=t+abs(com_list[i]-cm)
                    p_n=p_n+1;
                    
                if 1:
                    for a in gray_list:
                        cm=a
                        res.append(abs(com_list[i]-cm))
                        com_list[i]=cm
                        i=i+1 

                        img = Image.new( 'L', (128,64), "black")
                        pixels = img.load()
                        k=0
                        for j in range(img.size[1]):
                            for i in range(img.size[0]):
                                pixels[i,j] =res[k]
                                k=k+1

                        name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\bin_nf\\data_'+str(z)+'\\'+str(s) 
                        img.save(name)


1


IndexError: list index out of range

In [6]:
import math
import numpy as np
from PIL import Image
import os
import random
mm=0
for z in range(1,101):
    cnt=0
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\bin_f1\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
        



        for x in range(1,number_of_files-1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                t=0
                p_n=0;
                for a in gray_list: 
                    cm=a
                    t=t+abs(com_list[i]-cm)
                    p_n=p_n+1
                    i=i+1
                
                #print(t/p_n)
                i=0
                if(t/p_n>15.0):
                    cnt=cnt+1
                  
                    for a in gray_list:
                        cm=a
                        res.append(abs(com_list[i]-cm))
                        com_list[i]=cm
                        i=i+1
                    img = Image.new( 'L', (128,64), "black")
                    pixels = img.load()
                    k=0
                    ''''for j in range(img.size[1]):
                        for i in range(img.size[0]):
                            pixels[i,j] =res[k]
                            k=k+1
                    mm=mm+1
                    name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\f_selected\\'+str(mm)+'.jpg'
                
                    img.save(name)
                    '''
        print(str(z)+ ": " +str(cnt))
        
        

IndexError: list index out of range

In [36]:
import math
import numpy as np
from PIL import Image
import os
import random
mm=0
for z in range(1,501):
    cnt=0
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
        



        for x in range(number_of_files-1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                t=0
                p_n=0;
                for a in gray_list: 
                    cm=a
                    t=t+abs(com_list[i]-cm)
                    p_n=p_n+1
                    i=i+1
                
                #print(t/p_n)
                i=0
                if(t/p_n>15.0):
                    cnt=cnt+1
                  
                    for a in gray_list:
                        cm=a
                        res.append(abs(com_list[i]-cm))
                        com_list[i]=cm
                        i=i+1
                    img = Image.new( 'L', (128,64), "black")
                    pixels = img.load()
                    k=0
                    for j in range(img.size[1]):
                        for i in range(img.size[0]):
                            pixels[i,j] =res[k]
                            k=k+1
                    mm=mm+1
                    name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\nf_selected\\'+str(mm)+'.jpg'
                
                    img.save(name)
                    
        print(str(z)+ ": " +str(cnt))
        
        

1: 24
2: 24
3: 3
4: 3
5: 0
6: 12
7: 4
8: 1
9: 9
10: 5
11: 5
12: 2
13: 4
14: 4
15: 1
16: 1
17: 2
18: 3
19: 5
20: 6
21: 0
22: 4
23: 7
24: 0
25: 9
26: 10
27: 1
28: 11
29: 2
30: 4
31: 2
32: 0
33: 4
34: 6
35: 11
36: 5
37: 17
38: 6
39: 5
40: 16
41: 12
42: 17
43: 18
44: 1
45: 2
46: 2
47: 10
48: 6
49: 2
50: 2
51: 1
52: 1
53: 14
54: 4
55: 15
56: 16
57: 0
58: 2
59: 5
60: 5
61: 2
62: 6
63: 8
64: 18
65: 5
66: 5
67: 5
68: 20
69: 13
70: 26
71: 15
72: 21
73: 1
74: 1
75: 3
76: 25
77: 21
78: 14
79: 19
80: 20
81: 9
82: 1
83: 6
84: 18
85: 18
86: 29
87: 14
88: 4
89: 7
90: 25
91: 10
92: 11
93: 3
94: 6
95: 31
96: 3
97: 0
98: 20
99: 25
100: 4
101: 3
102: 0
103: 0
104: 1
105: 2
106: 0
107: 4
108: 1
109: 4
110: 2
111: 0
112: 2
113: 7
114: 4
115: 5
116: 11
117: 1
118: 10
119: 15
120: 13
121: 8
122: 5
123: 16
124: 16
125: 17
126: 1
127: 10
128: 0
129: 0
130: 1
131: 1
132: 0
133: 12
134: 0
135: 10
136: 16
137: 2
138: 17
139: 9
140: 13
141: 0
142: 0
143: 11
144: 4
145: 7
146: 5
147: 5
148: 16
149: 10
150: 12
151: 

In [17]:
import pandas as pd

In [20]:
pwd

'C:\\Users\\Asus\\Desktop\\violence_detection\\hf\\data_1'

In [23]:
data=pd.read_csv("C:\\Users\\Asus\\Desktop\\violence_detection\\hf\\hocky.csv", error_bad_lines=False)

b'Skipping line 4: expected 1 fields, saw 2\nSkipping line 6: expected 1 fields, saw 3\nSkipping line 16: expected 1 fields, saw 2\nSkipping line 17: expected 1 fields, saw 2\nSkipping line 19: expected 1 fields, saw 2\nSkipping line 20: expected 1 fields, saw 2\nSkipping line 26: expected 1 fields, saw 3\nSkipping line 34: expected 1 fields, saw 3\nSkipping line 43: expected 1 fields, saw 2\nSkipping line 45: expected 1 fields, saw 3\n'


UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9d in position 1: invalid start byte

In [31]:
import math
import numpy as np
from PIL import Image
import os
import random
import csv
import pandas as pd
com_list=[]
for z in range(1,3):
    print(z)
    if z>0:
        
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\hf\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)

        for x in range(number_of_files):
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            h_list= list(im.getdata())
            h_list.append(0)
            #print(h_list)
            
            df = df.append(pd.DataFrame([h_list]))
            #df2.to_csv("login.csv", index=False)
            #df = pd.DataFrame(h_list, columns=["colummn"+str(x)])
            df.to_csv("C:\\Users\\Asus\\Desktop\\violence_detection\\hf\\hocky.csv", index=False)
            
'''             
for z in range(1,501):
    print(z)
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\hk\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                for a in gray_list:
                    cm=a
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 
                img = Image.new( 'L', (128,64), "black")
                pixels = img.load()
                k=0
                for j in range(img.size[1]):
                    for i in range(img.size[0]):
                        pixels[i,j] =res[k]
                        k=k+1
                name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)+'\\'+str(s) 
                img.save(name)
                
'''

1


C:\Users\Asus\Anaconda3\Anaconda3\lib\site-packages\pandas\core\indexes\api.py:87: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  result = result.union(other)


KeyboardInterrupt: 

In [ ]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
X=[]
y=[]
for z in range(1,501):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            #print(hog_lst)
            X.append(hog_lst)
            y.append(1)
for z in range(1,501):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            X.append(hog_lst)
            y.append(0)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34


In [3]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
acc=0
tot=0
for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            acc=acc+1
            print("fight")
        else:
            print("non fight")

            

for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            print("fight")
        else:
            acc=acc+1
            print("non fight")

acuracy=(acc/tot)*100
print(acuracy)

1
2
3
4
5


AttributeError: 'int' object has no attribute 'predict'

In [45]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
X=[]
y=[]
if 1:
    
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\h_f_selected\\'
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files):
            res=[]
            #print(x)
            s=str(x)+'.jpg'
            print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            #print(hog_lst)
            X.append(hog_lst)
            y.append(1)
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\h_nf_selected\\'
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files):
            res=[]
            #print(x)
            s=str(x)+'.jpg'
            print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            #print(hog_lst)
            X.append(hog_lst)
            y.append(0)


1.jpg
2.jpg
3.jpg
4.jpg
5.jpg
6.jpg
7.jpg
8.jpg
9.jpg
10.jpg
11.jpg
12.jpg
13.jpg
14.jpg
15.jpg
16.jpg
17.jpg
18.jpg
19.jpg
20.jpg
21.jpg
22.jpg
23.jpg
24.jpg
25.jpg
26.jpg
27.jpg
28.jpg
29.jpg
30.jpg
31.jpg
32.jpg
33.jpg
34.jpg
35.jpg
36.jpg
37.jpg
38.jpg
39.jpg
40.jpg
41.jpg
42.jpg
43.jpg
44.jpg
45.jpg
46.jpg
47.jpg
48.jpg
49.jpg
50.jpg
51.jpg
52.jpg
53.jpg
54.jpg
55.jpg
56.jpg
57.jpg
58.jpg
59.jpg
60.jpg
61.jpg
62.jpg
63.jpg
64.jpg
65.jpg
66.jpg
67.jpg
68.jpg
69.jpg
70.jpg
71.jpg
72.jpg
73.jpg
74.jpg
75.jpg
76.jpg
77.jpg
78.jpg
79.jpg
80.jpg
81.jpg
82.jpg
83.jpg
84.jpg
85.jpg
86.jpg
87.jpg
88.jpg
89.jpg
90.jpg
91.jpg
92.jpg
93.jpg
94.jpg
95.jpg
96.jpg
97.jpg
98.jpg
99.jpg
100.jpg
101.jpg
102.jpg
103.jpg
104.jpg
105.jpg
106.jpg
107.jpg
108.jpg
109.jpg
110.jpg
111.jpg
112.jpg
113.jpg
114.jpg
115.jpg
116.jpg
117.jpg
118.jpg
119.jpg
120.jpg
121.jpg
122.jpg
123.jpg
124.jpg
125.jpg
126.jpg
127.jpg
128.jpg
129.jpg
130.jpg
131.jpg
132.jpg
133.jpg
134.jpg
135.jpg
136.jpg
137.jpg
138.jpg
139.

1177.jpg
1178.jpg
1179.jpg
1180.jpg
1181.jpg
1182.jpg
1183.jpg
1184.jpg
1185.jpg
1186.jpg
1187.jpg
1188.jpg
1189.jpg
1190.jpg
1191.jpg
1192.jpg
1193.jpg
1194.jpg
1195.jpg
1196.jpg
1197.jpg
1198.jpg
1199.jpg
1200.jpg
1201.jpg
1202.jpg
1203.jpg
1204.jpg
1205.jpg
1206.jpg
1207.jpg
1208.jpg
1209.jpg
1210.jpg
1211.jpg
1212.jpg
1213.jpg
1214.jpg
1215.jpg
1216.jpg
1217.jpg
1218.jpg
1219.jpg
1220.jpg
1221.jpg
1222.jpg
1223.jpg
1224.jpg
1225.jpg
1226.jpg
1227.jpg
1228.jpg
1229.jpg
1230.jpg
1231.jpg
1232.jpg
1233.jpg
1234.jpg
1235.jpg
1236.jpg
1237.jpg
1238.jpg
1239.jpg
1240.jpg
1241.jpg
1242.jpg
1243.jpg
1244.jpg
1245.jpg
1246.jpg
1247.jpg
1248.jpg
1249.jpg
1250.jpg
1251.jpg
1252.jpg
1253.jpg
1254.jpg
1255.jpg
1256.jpg
1257.jpg
1258.jpg
1259.jpg
1260.jpg
1261.jpg
1262.jpg
1263.jpg
1264.jpg
1265.jpg
1266.jpg
1267.jpg
1268.jpg
1269.jpg
1270.jpg
1271.jpg
1272.jpg
1273.jpg
1274.jpg
1275.jpg
1276.jpg
1277.jpg
1278.jpg
1279.jpg
1280.jpg
1281.jpg
1282.jpg
1283.jpg
1284.jpg
1285.jpg
1286.jpg
1287.jpg
1

2271.jpg
2272.jpg
2273.jpg
2274.jpg
2275.jpg
2276.jpg
2277.jpg
2278.jpg
2279.jpg
2280.jpg
2281.jpg
2282.jpg
2283.jpg
2284.jpg
2285.jpg
2286.jpg
2287.jpg
2288.jpg
2289.jpg
2290.jpg
2291.jpg
2292.jpg
2293.jpg
2294.jpg
2295.jpg
2296.jpg
2297.jpg
2298.jpg
2299.jpg
2300.jpg
2301.jpg
2302.jpg
2303.jpg
2304.jpg
2305.jpg
2306.jpg
2307.jpg
2308.jpg
2309.jpg
2310.jpg
2311.jpg
2312.jpg
2313.jpg
2314.jpg
2315.jpg
2316.jpg
2317.jpg
2318.jpg
2319.jpg
2320.jpg
2321.jpg
2322.jpg
2323.jpg
2324.jpg
2325.jpg
2326.jpg
2327.jpg
2328.jpg
2329.jpg
2330.jpg
2331.jpg
2332.jpg
2333.jpg
2334.jpg
2335.jpg
2336.jpg
2337.jpg
2338.jpg
2339.jpg
2340.jpg
2341.jpg
2342.jpg
2343.jpg
2344.jpg
2345.jpg
2346.jpg
2347.jpg
2348.jpg
2349.jpg
2350.jpg
2351.jpg
2352.jpg
2353.jpg
2354.jpg
2355.jpg
2356.jpg
2357.jpg
2358.jpg
2359.jpg
2360.jpg
2361.jpg
2362.jpg
2363.jpg
2364.jpg
2365.jpg
2366.jpg
2367.jpg
2368.jpg
2369.jpg
2370.jpg
2371.jpg
2372.jpg
2373.jpg
2374.jpg
2375.jpg
2376.jpg
2377.jpg
2378.jpg
2379.jpg
2380.jpg
2381.jpg
2

3406.jpg
3407.jpg
3408.jpg
3409.jpg
3410.jpg
3411.jpg
3412.jpg
3413.jpg
3414.jpg
3415.jpg
3416.jpg
3417.jpg
3418.jpg
3419.jpg
3420.jpg
3421.jpg
3422.jpg
3423.jpg
3424.jpg
3425.jpg
3426.jpg
3427.jpg
3428.jpg
3429.jpg
3430.jpg
3431.jpg
3432.jpg
3433.jpg
3434.jpg
3435.jpg
3436.jpg
3437.jpg
3438.jpg
3439.jpg
3440.jpg
3441.jpg
3442.jpg
3443.jpg
3444.jpg
3445.jpg
3446.jpg
3447.jpg
3448.jpg
3449.jpg
3450.jpg
3451.jpg
3452.jpg
3453.jpg
3454.jpg
3455.jpg
3456.jpg
3457.jpg
3458.jpg
3459.jpg
3460.jpg
3461.jpg
3462.jpg
3463.jpg
3464.jpg
3465.jpg
3466.jpg
3467.jpg
3468.jpg
3469.jpg
3470.jpg
3471.jpg
3472.jpg
3473.jpg
3474.jpg
3475.jpg
3476.jpg
3477.jpg
3478.jpg
3479.jpg
3480.jpg
3481.jpg
3482.jpg
3483.jpg
3484.jpg
3485.jpg
3486.jpg
3487.jpg
3488.jpg
3489.jpg
3490.jpg
3491.jpg
3492.jpg
3493.jpg
3494.jpg
3495.jpg
3496.jpg
3497.jpg
3498.jpg
3499.jpg
3500.jpg
3501.jpg
3502.jpg
3503.jpg
3504.jpg
3505.jpg
3506.jpg
3507.jpg
3508.jpg
3509.jpg
3510.jpg
3511.jpg
3512.jpg
3513.jpg
3514.jpg
3515.jpg
3516.jpg
3

4322.jpg
4323.jpg
4324.jpg
4325.jpg
4326.jpg
4327.jpg
4328.jpg
4329.jpg
4330.jpg
4331.jpg
4332.jpg
4333.jpg
4334.jpg
4335.jpg
4336.jpg
4337.jpg
4338.jpg
4339.jpg
4340.jpg
4341.jpg
4342.jpg
4343.jpg
4344.jpg
4345.jpg
4346.jpg
4347.jpg
4348.jpg
4349.jpg
4350.jpg
4351.jpg
4352.jpg
4353.jpg
4354.jpg
4355.jpg
4356.jpg
4357.jpg
4358.jpg
4359.jpg
4360.jpg
4361.jpg
4362.jpg
4363.jpg
4364.jpg
4365.jpg
4366.jpg
4367.jpg
4368.jpg
4369.jpg
4370.jpg
4371.jpg
4372.jpg
4373.jpg
4374.jpg
4375.jpg
4376.jpg
4377.jpg
4378.jpg
4379.jpg
4380.jpg
4381.jpg
4382.jpg
4383.jpg
4384.jpg
4385.jpg
4386.jpg
4387.jpg
4388.jpg
4389.jpg
4390.jpg
4391.jpg
4392.jpg
4393.jpg
4394.jpg
4395.jpg
4396.jpg
4397.jpg
4398.jpg
4399.jpg
4400.jpg
4401.jpg
4402.jpg
4403.jpg
4404.jpg
4405.jpg
4406.jpg
4407.jpg
4408.jpg
4409.jpg
4410.jpg
4411.jpg
4412.jpg
4413.jpg
4414.jpg
4415.jpg
4416.jpg
4417.jpg
4418.jpg
4419.jpg
4420.jpg
4421.jpg
4422.jpg
4423.jpg
4424.jpg
4425.jpg
4426.jpg
4427.jpg
4428.jpg
4429.jpg
4430.jpg
4431.jpg
4432.jpg
4

5241.jpg
5242.jpg
5243.jpg
5244.jpg
5245.jpg
5246.jpg
5247.jpg
5248.jpg
5249.jpg
5250.jpg
5251.jpg
5252.jpg
5253.jpg
5254.jpg
5255.jpg
5256.jpg
5257.jpg
5258.jpg
5259.jpg
5260.jpg
5261.jpg
5262.jpg
5263.jpg
5264.jpg
5265.jpg
5266.jpg
5267.jpg
5268.jpg
5269.jpg
5270.jpg
5271.jpg
5272.jpg
5273.jpg
5274.jpg
5275.jpg
5276.jpg
5277.jpg
5278.jpg
5279.jpg
5280.jpg
5281.jpg
5282.jpg
5283.jpg
5284.jpg
5285.jpg
5286.jpg
5287.jpg
5288.jpg
5289.jpg
5290.jpg
5291.jpg
5292.jpg
5293.jpg
5294.jpg
5295.jpg
5296.jpg
5297.jpg
5298.jpg
5299.jpg
5300.jpg
5301.jpg
5302.jpg
5303.jpg
5304.jpg
5305.jpg
5306.jpg
5307.jpg
5308.jpg
5309.jpg
5310.jpg
5311.jpg
5312.jpg
5313.jpg
5314.jpg
5315.jpg
5316.jpg
5317.jpg
5318.jpg
5319.jpg
5320.jpg
5321.jpg
5322.jpg
5323.jpg
5324.jpg
5325.jpg
5326.jpg
5327.jpg
5328.jpg
5329.jpg
5330.jpg
5331.jpg
5332.jpg
5333.jpg
5334.jpg
5335.jpg
5336.jpg
5337.jpg
5338.jpg
5339.jpg
5340.jpg
5341.jpg
5342.jpg
5343.jpg
5344.jpg
5345.jpg
5346.jpg
5347.jpg
5348.jpg
5349.jpg
5350.jpg
5351.jpg
5

6172.jpg
6173.jpg
6174.jpg
6175.jpg
6176.jpg
6177.jpg
6178.jpg
6179.jpg
6180.jpg
6181.jpg
6182.jpg
6183.jpg
6184.jpg
6185.jpg
6186.jpg
6187.jpg
6188.jpg
6189.jpg
6190.jpg
6191.jpg
6192.jpg
6193.jpg
6194.jpg
6195.jpg
6196.jpg
6197.jpg
6198.jpg
6199.jpg
6200.jpg
6201.jpg
6202.jpg
6203.jpg
6204.jpg
6205.jpg
6206.jpg
6207.jpg
6208.jpg
6209.jpg
6210.jpg
6211.jpg
6212.jpg
6213.jpg
6214.jpg
6215.jpg
6216.jpg
6217.jpg
6218.jpg
6219.jpg
6220.jpg
6221.jpg
6222.jpg
6223.jpg
6224.jpg
6225.jpg
6226.jpg
6227.jpg
6228.jpg
6229.jpg
6230.jpg
6231.jpg
6232.jpg
6233.jpg
6234.jpg
6235.jpg
6236.jpg
6237.jpg
6238.jpg
6239.jpg
6240.jpg
6241.jpg
6242.jpg
6243.jpg
6244.jpg
6245.jpg
6246.jpg
6247.jpg
6248.jpg
6249.jpg
6250.jpg
6251.jpg
6252.jpg
6253.jpg
6254.jpg
6255.jpg
6256.jpg
6257.jpg
6258.jpg
6259.jpg
6260.jpg
6261.jpg
6262.jpg
6263.jpg
6264.jpg
6265.jpg
6266.jpg
6267.jpg
6268.jpg
6269.jpg
6270.jpg
6271.jpg
6272.jpg
6273.jpg
6274.jpg
6275.jpg
6276.jpg
6277.jpg
6278.jpg
6279.jpg
6280.jpg
6281.jpg
6282.jpg
6

7253.jpg
7254.jpg
7255.jpg
7256.jpg
7257.jpg
7258.jpg
7259.jpg
7260.jpg
7261.jpg
7262.jpg
7263.jpg
7264.jpg
7265.jpg
7266.jpg
7267.jpg
7268.jpg
7269.jpg
7270.jpg
7271.jpg
7272.jpg
7273.jpg
7274.jpg
7275.jpg
7276.jpg
7277.jpg
7278.jpg
7279.jpg
7280.jpg
7281.jpg
7282.jpg
7283.jpg
7284.jpg
7285.jpg
7286.jpg
7287.jpg
7288.jpg
7289.jpg
7290.jpg
7291.jpg
7292.jpg
7293.jpg
7294.jpg
7295.jpg
7296.jpg
7297.jpg
7298.jpg
7299.jpg
7300.jpg
7301.jpg
7302.jpg
7303.jpg
7304.jpg
7305.jpg
7306.jpg
7307.jpg
7308.jpg
7309.jpg
7310.jpg
7311.jpg
7312.jpg
7313.jpg
7314.jpg
7315.jpg
7316.jpg
7317.jpg
7318.jpg
7319.jpg
7320.jpg
7321.jpg
7322.jpg
7323.jpg
7324.jpg
7325.jpg
7326.jpg
7327.jpg
7328.jpg
7329.jpg
7330.jpg
7331.jpg
7332.jpg
7333.jpg
7334.jpg
7335.jpg
7336.jpg
7337.jpg
7338.jpg
7339.jpg
7340.jpg
7341.jpg
7342.jpg
7343.jpg
7344.jpg
7345.jpg
7346.jpg
7347.jpg
7348.jpg
7349.jpg
7350.jpg
7351.jpg
7352.jpg
7353.jpg
7354.jpg
7355.jpg
7356.jpg
7357.jpg
7358.jpg
7359.jpg
7360.jpg
7361.jpg
7362.jpg
7363.jpg
7

8199.jpg
8200.jpg
8201.jpg
8202.jpg
8203.jpg
8204.jpg
8205.jpg
8206.jpg
8207.jpg
8208.jpg
8209.jpg
8210.jpg
8211.jpg
8212.jpg
8213.jpg
8214.jpg
8215.jpg
8216.jpg
8217.jpg
8218.jpg
8219.jpg
8220.jpg
8221.jpg
8222.jpg
8223.jpg
8224.jpg
8225.jpg
8226.jpg
8227.jpg
8228.jpg
8229.jpg
8230.jpg
8231.jpg
8232.jpg
8233.jpg
8234.jpg
8235.jpg
8236.jpg
8237.jpg
8238.jpg
8239.jpg
8240.jpg
8241.jpg
8242.jpg
8243.jpg
8244.jpg
8245.jpg
8246.jpg
8247.jpg
8248.jpg
8249.jpg
8250.jpg
8251.jpg
8252.jpg
8253.jpg
8254.jpg
8255.jpg
8256.jpg
8257.jpg
8258.jpg
8259.jpg
8260.jpg
8261.jpg
8262.jpg
8263.jpg
8264.jpg
8265.jpg
8266.jpg
8267.jpg
8268.jpg
8269.jpg
8270.jpg
8271.jpg
8272.jpg
8273.jpg
8274.jpg
8275.jpg
8276.jpg
8277.jpg
8278.jpg
8279.jpg
8280.jpg
8281.jpg
8282.jpg
8283.jpg
8284.jpg
8285.jpg
8286.jpg
8287.jpg
8288.jpg
8289.jpg
8290.jpg
8291.jpg
8292.jpg
8293.jpg
8294.jpg
8295.jpg
8296.jpg
8297.jpg
8298.jpg
8299.jpg
8300.jpg
8301.jpg
8302.jpg
8303.jpg
8304.jpg
8305.jpg
8306.jpg
8307.jpg
8308.jpg
8309.jpg
8

363.jpg
364.jpg
365.jpg
366.jpg
367.jpg
368.jpg
369.jpg
370.jpg
371.jpg
372.jpg
373.jpg
374.jpg
375.jpg
376.jpg
377.jpg
378.jpg
379.jpg
380.jpg
381.jpg
382.jpg
383.jpg
384.jpg
385.jpg
386.jpg
387.jpg
388.jpg
389.jpg
390.jpg
391.jpg
392.jpg
393.jpg
394.jpg
395.jpg
396.jpg
397.jpg
398.jpg
399.jpg
400.jpg
401.jpg
402.jpg
403.jpg
404.jpg
405.jpg
406.jpg
407.jpg
408.jpg
409.jpg
410.jpg
411.jpg
412.jpg
413.jpg
414.jpg
415.jpg
416.jpg
417.jpg
418.jpg
419.jpg
420.jpg
421.jpg
422.jpg
423.jpg
424.jpg
425.jpg
426.jpg
427.jpg
428.jpg
429.jpg
430.jpg
431.jpg
432.jpg
433.jpg
434.jpg
435.jpg
436.jpg
437.jpg
438.jpg
439.jpg
440.jpg
441.jpg
442.jpg
443.jpg
444.jpg
445.jpg
446.jpg
447.jpg
448.jpg
449.jpg
450.jpg
451.jpg
452.jpg
453.jpg
454.jpg
455.jpg
456.jpg
457.jpg
458.jpg
459.jpg
460.jpg
461.jpg
462.jpg
463.jpg
464.jpg
465.jpg
466.jpg
467.jpg
468.jpg
469.jpg
470.jpg
471.jpg
472.jpg
473.jpg
474.jpg
475.jpg
476.jpg
477.jpg
478.jpg
479.jpg
480.jpg
481.jpg
482.jpg
483.jpg
484.jpg
485.jpg
486.jpg
487.jpg


1408.jpg
1409.jpg
1410.jpg
1411.jpg
1412.jpg
1413.jpg
1414.jpg
1415.jpg
1416.jpg
1417.jpg
1418.jpg
1419.jpg
1420.jpg
1421.jpg
1422.jpg
1423.jpg
1424.jpg
1425.jpg
1426.jpg
1427.jpg
1428.jpg
1429.jpg
1430.jpg
1431.jpg
1432.jpg
1433.jpg
1434.jpg
1435.jpg
1436.jpg
1437.jpg
1438.jpg
1439.jpg
1440.jpg
1441.jpg
1442.jpg
1443.jpg
1444.jpg
1445.jpg
1446.jpg
1447.jpg
1448.jpg
1449.jpg
1450.jpg
1451.jpg
1452.jpg
1453.jpg
1454.jpg
1455.jpg
1456.jpg
1457.jpg
1458.jpg
1459.jpg
1460.jpg
1461.jpg
1462.jpg
1463.jpg
1464.jpg
1465.jpg
1466.jpg
1467.jpg
1468.jpg
1469.jpg
1470.jpg
1471.jpg
1472.jpg
1473.jpg
1474.jpg
1475.jpg
1476.jpg
1477.jpg
1478.jpg
1479.jpg
1480.jpg
1481.jpg
1482.jpg
1483.jpg
1484.jpg
1485.jpg
1486.jpg
1487.jpg
1488.jpg
1489.jpg
1490.jpg
1491.jpg
1492.jpg
1493.jpg
1494.jpg
1495.jpg
1496.jpg
1497.jpg
1498.jpg
1499.jpg
1500.jpg
1501.jpg
1502.jpg
1503.jpg
1504.jpg
1505.jpg
1506.jpg
1507.jpg
1508.jpg
1509.jpg
1510.jpg
1511.jpg
1512.jpg
1513.jpg
1514.jpg
1515.jpg
1516.jpg
1517.jpg
1518.jpg
1

2337.jpg
2338.jpg
2339.jpg
2340.jpg
2341.jpg
2342.jpg
2343.jpg
2344.jpg
2345.jpg
2346.jpg
2347.jpg
2348.jpg
2349.jpg
2350.jpg
2351.jpg
2352.jpg
2353.jpg
2354.jpg
2355.jpg
2356.jpg
2357.jpg
2358.jpg
2359.jpg
2360.jpg
2361.jpg
2362.jpg
2363.jpg
2364.jpg
2365.jpg
2366.jpg
2367.jpg
2368.jpg
2369.jpg
2370.jpg
2371.jpg
2372.jpg
2373.jpg
2374.jpg
2375.jpg
2376.jpg
2377.jpg
2378.jpg
2379.jpg
2380.jpg
2381.jpg
2382.jpg
2383.jpg
2384.jpg
2385.jpg
2386.jpg
2387.jpg
2388.jpg
2389.jpg
2390.jpg
2391.jpg
2392.jpg
2393.jpg
2394.jpg
2395.jpg
2396.jpg
2397.jpg
2398.jpg
2399.jpg
2400.jpg
2401.jpg
2402.jpg
2403.jpg
2404.jpg
2405.jpg
2406.jpg
2407.jpg
2408.jpg
2409.jpg
2410.jpg
2411.jpg
2412.jpg
2413.jpg
2414.jpg
2415.jpg
2416.jpg
2417.jpg
2418.jpg
2419.jpg
2420.jpg
2421.jpg
2422.jpg
2423.jpg
2424.jpg
2425.jpg
2426.jpg
2427.jpg
2428.jpg
2429.jpg
2430.jpg
2431.jpg
2432.jpg
2433.jpg
2434.jpg
2435.jpg
2436.jpg
2437.jpg
2438.jpg
2439.jpg
2440.jpg
2441.jpg
2442.jpg
2443.jpg
2444.jpg
2445.jpg
2446.jpg
2447.jpg
2

3328.jpg
3329.jpg
3330.jpg
3331.jpg
3332.jpg
3333.jpg
3334.jpg
3335.jpg
3336.jpg
3337.jpg
3338.jpg
3339.jpg
3340.jpg
3341.jpg
3342.jpg
3343.jpg
3344.jpg
3345.jpg
3346.jpg
3347.jpg
3348.jpg
3349.jpg
3350.jpg
3351.jpg
3352.jpg
3353.jpg
3354.jpg
3355.jpg
3356.jpg
3357.jpg
3358.jpg
3359.jpg
3360.jpg
3361.jpg
3362.jpg
3363.jpg
3364.jpg
3365.jpg
3366.jpg
3367.jpg
3368.jpg
3369.jpg
3370.jpg
3371.jpg
3372.jpg
3373.jpg
3374.jpg
3375.jpg
3376.jpg
3377.jpg
3378.jpg
3379.jpg
3380.jpg
3381.jpg
3382.jpg
3383.jpg
3384.jpg
3385.jpg
3386.jpg
3387.jpg
3388.jpg
3389.jpg
3390.jpg
3391.jpg
3392.jpg
3393.jpg
3394.jpg
3395.jpg
3396.jpg
3397.jpg
3398.jpg
3399.jpg
3400.jpg
3401.jpg
3402.jpg
3403.jpg
3404.jpg
3405.jpg
3406.jpg
3407.jpg
3408.jpg
3409.jpg
3410.jpg
3411.jpg
3412.jpg
3413.jpg
3414.jpg
3415.jpg
3416.jpg
3417.jpg
3418.jpg
3419.jpg
3420.jpg
3421.jpg
3422.jpg
3423.jpg
3424.jpg
3425.jpg
3426.jpg
3427.jpg
3428.jpg
3429.jpg
3430.jpg
3431.jpg
3432.jpg
3433.jpg
3434.jpg
3435.jpg
3436.jpg
3437.jpg
3438.jpg
3

In [46]:
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]



In [47]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, stratify=y)

In [48]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support

In [49]:
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(gamma='auto',kernel='linear')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
precision_recall_fscore_support(y_test, y_pred, average='binary')

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 447
Accuracy: 0.88
[[ 834  208]
 [ 239 2429]]


0.7045657149206909

In [50]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9211224876753887, 0.9104197901049476, 0.9157398680490104, None)

In [51]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='rbf')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 651
Accuracy: 0.82


0.5377630186534647

In [53]:
confusion_matrix(y_test, y_pred)

array([[ 433,  609],
       [  42, 2626]], dtype=int64)

In [52]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.8117465224111283, 0.9842578710644677, 0.8897170930035575, None)

In [64]:
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
print(matthews_corrcoef(y_test, y_pred))

Misclassified samples: 471
Accuracy: 0.87
[[ 830  212]
 [ 259 2409]]
0.6903154161885338


In [65]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9191148416634872, 0.9029235382308846, 0.9109472490073739, None)

In [66]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='poly')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1042
Accuracy: 0.72
[[   0 1042]
 [   0 2668]]


C:\Users\Asus\Anaconda3\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:538: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)


0.0

In [67]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.7191374663072776, 1.0, 0.8366259015365318, None)

In [68]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='sigmoid')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 828
Accuracy: 0.78
[[ 222  820]
 [   8 2660]]


0.3914738777775588

In [69]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.764367816091954, 0.9970014992503748, 0.8653220559531556, None)

In [70]:
from sklearn.linear_model import LogisticRegression

ppn = LogisticRegression(random_state=1)
ppn = ppn.fit(X_train1, y_train)
y_pred = ppn.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 381
Accuracy: 0.90
[[ 819  223]
 [ 158 2510]]


0.741575763088382

In [71]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9184046834979875, 0.9407796101949025, 0.9294575078689132, None)

In [56]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 519
Accuracy: 0.86
[[ 730  312]
 [ 207 2461]]


0.6444108510573728

In [57]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.8874864767399928, 0.9224137931034483, 0.9046131225877596, None)

In [58]:
import sklearn
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
clf = LDA()
clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 548
Accuracy: 0.85
[[ 795  247]
 [ 301 2367]]


0.6404330889118218

In [59]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9055087987758225, 0.8871814092953523, 0.8962514199166981, None)

In [60]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
print(matthews_corrcoef(y_test, y_pred))

Misclassified samples: 689
Accuracy: 0.81
[[ 759  283]
 [ 406 2262]]
0.5579792382909518


In [61]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.8888015717092338, 0.8478260869565217, 0.8678304239401496, None)

In [62]:
from sklearn.neural_network import MLPClassifier
gnb = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(13, 2), random_state=1)
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
print(matthews_corrcoef(y_test, y_pred))

Misclassified samples: 471
Accuracy: 0.87
[[ 830  212]
 [ 259 2409]]
0.6903154161885338


In [63]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9191148416634872, 0.9029235382308846, 0.9109472490073739, None)

In [54]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
y_pred = neigh.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 221
Accuracy: 0.94
[[ 858  184]
 [  37 2631]]


0.8503914704323423

In [55]:
precision_recall_fscore_support(y_test, y_pred, average='binary')

(0.9346358792184725, 0.9861319340329835, 0.9596935983950391, None)