In [1]:
cd C:\\Users\\ASUS\\Desktop\\violence_detection

C:\Users\ASUS\Desktop\violence_detection


In [26]:
import cv2
import numpy as np
import os
import math
import numpy as np
from PIL import Image
width = 128
height =64
dim = (width, height)

for frm_no in range(1,3):
    dr='C:/Users/Asus/Desktop/violence_detection/hocky_fight/'+'fi'+str(frm_no)+'_xvid.avi'
    print(dr)
    cap = cv2.VideoCapture(dr)
    fl='data_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()

for frm_no in range(1,501):
    dr='C:/Users/Asus/Desktop/violence_detection/hocky_fight/'+'fi'+str(frm_no)+'_xvid.avi'
    cap = cv2.VideoCapture(dr)
    fl='ndata_'+str(frm_no)
    try:
        if not os.path.exists(fl):
            os.makedirs(fl)
    except OSError:
        print ('Error: Creating directory of data')

    currentFrame = 0
    while(cap.isOpened()):
        ret, frm = cap.read()
        
        if ret == True:
            frame = cv2.resize(frm, dim, interpolation = cv2.INTER_AREA)
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            ret,thresh = cv2.threshold(gray,127,255,cv2.THRESH_BINARY)
            name = './'+fl+'/frame' + str(currentFrame) + '.jpg'
            #print ('Creating...' + name)
            cv2.imwrite(name, thresh)


            currentFrame += 1
        else:
            break

    cap.release()
    cv2.destroyAllWindows()
'''

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi1_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi2_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi3_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi4_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi5_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi6_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi7_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi8_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi9_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi10_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi11_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi12_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi13_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi14_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi15_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi16_xvi
C:/Users/Asus/Des

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi141_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi142_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi143_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi144_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi145_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi146_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi147_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi148_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi149_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi150_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi151_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi152_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi153_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi154_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi155_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi279_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi280_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi281_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi282_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi283_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi284_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi285_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi286_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi287_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi288_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi289_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi290_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi291_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi292_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi293_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi

C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi414_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi415_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi416_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi417_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi418_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi419_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi420_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi421_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi422_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi423_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi424_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi425_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi426_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi427_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi428_xvi
C:/Users/Asus/Desktop/violence_detection/hocky_fight/fi

In [27]:
import math
import numpy as np
from PIL import Image
import os
import random
for z in range(1,501):
    print(z)
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\fight\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
        



        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                for a in gray_list:
                    cm=a
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 
                img = Image.new( 'L', (128,64), "black")
                pixels = img.load()
                k=0
                for j in range(img.size[1]):
                    for i in range(img.size[0]):
                        pixels[i,j] =res[k]
                        k=k+1
                
                name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\bin_f\\data_'+str(z)+'\\'+str(s) 
                img.save(name)

                
for z in range(1,501):
    print(z)
    if z>0:
        com_list=[]
        
        ss='C:\\Users\\Asus\\Desktop\\violence_detection\\non_fight\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(number_of_files)
#print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(number_of_files):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            im = Image.open(s, 'r')
            gray_list= list(im.getdata())
            i=0
            if x == 0:
                i=0
                for a in gray_list:
                    com_list.insert(i,a)
                    i=i+1   
            else:
                i=0
                for a in gray_list:
                    cm=a
                    res.append(abs(com_list[i]-cm))
                    com_list[i]=cm
                    i=i+1 
                img = Image.new( 'L', (128,64), "black")
                pixels = img.load()
                k=0
                for j in range(img.size[1]):
                    for i in range(img.size[0]):
                        pixels[i,j] =res[k]
                        k=k+1
                name =  'C:\\Users\\Asus\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)+'\\'+str(s) 
                img.save(name)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [2]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
X=[]
y=[]
for z in range(1,501):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            #print(hog_lst)
            X.append(hog_lst)
            y.append(1)
for z in range(1,501):
    print(z)
    if z>=0:
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()


        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            X.append(hog_lst)
            y.append(0)



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [3]:
import math
import numpy as np
from PIL import Image
import os
import random
import cv2
acc=0
tot=0
for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_f\\data_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            acc=acc+1
            print("fight")
        else:
            print("non fight")

            

for z in range(1,101):
    print(z)
    if z%5==0:
        tot=tot+1
        #com_list=[]
        
        ss='C:\\Users\\ASUS\\Desktop\\violence_detection\\bin_nf\\ndata_'+str(z)
        os.chdir(ss)
        
        file_list = os.listdir(ss) 
        number_of_files = len(file_list)
        #print(str(z) + " --- "+str(number_of_files))
        #lst=random.sample(range(1,number_of_files), 31)
        #lst.sort()

        cnt=0
        for x in range(1,number_of_files+1):
            res=[]
            #print(x)
            s='frame'+str(x)+'.jpg'
            #print(s)
            gray=cv2.imread(s)
            
            cell_size=(8,8)
            block_size=(2,2)
            nbins=9


            winSize = (gray.shape[1] // cell_size[1] * cell_size[1],gray.shape[0] // cell_size[0] * cell_size[0])
            blockSize = (block_size[1] * cell_size[1],block_size[0] * cell_size[0])
            blockStride = (cell_size[1], cell_size[0])
            cellSize = (cell_size[1], cell_size[0])
            nbins = 9
            derivAperture = 1
            winSigma = -1.
            histogramNormType = 0
            L2HysThreshold = 0.2
            gammaCorrection = 1
            nlevels = 64
            signedGradients = True
 
            hog = cv2.HOGDescriptor(winSize,blockSize,blockStride,cellSize,nbins,derivAperture,winSigma,histogramNormType,L2HysThreshold,gammaCorrection,nlevels, signedGradients)

            n_cells = (gray.shape[0] // cell_size[0], gray.shape[1] // cell_size[1])
            hog_feats = hog.compute(gray).ravel()
            hog_lst=hog_feats.tolist()
            rs=clf.predict([hog_lst])
            if rs[0]==1:
                cnt=cnt+1;
                    #print(cnt)
        #print(cnt)
        if cnt>(number_of_files/2):
            print("fight")
        else:
            acc=acc+1
            print("non fight")

acuracy=(acc/tot)*100
print(acuracy)

1
2
3
4
5


AttributeError: 'int' object has no attribute 'predict'

In [5]:
c =list( zip(X,y))
random.shuffle(c)
X = [i[0] for i in c]
y = [i[1] for i in c]



In [30]:
X=np.array(X)

In [31]:
X.shape

(40056, 3780)

In [32]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 100, whiten=True)
XX= pca.fit_transform(X)

In [33]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train, y_test = train_test_split(XX, y, test_size=0.3, random_state=1, stratify=y)

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(gamma='auto',kernel='linear')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)

print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1848
Accuracy: 0.85
[[5059  941]
 [ 907 5110]]


0.6924437248883282

In [36]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='rbf')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 788
Accuracy: 0.93


0.8688535588300802

In [37]:
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.metrics import accuracy_score

In [38]:
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 788
Accuracy: 0.93


0.8688535588300802

In [39]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='poly')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 592
Accuracy: 0.95
[[5530  470]
 [ 122 5895]]


0.9029806890353874

In [40]:
from sklearn import svm
clf = svm.SVC(gamma='auto',kernel='sigmoid')
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 2533
Accuracy: 0.79
[[4730 1270]
 [1263 4754]]


0.5784294107840848

In [41]:
from sklearn.linear_model import LogisticRegression

ppn = LogisticRegression(random_state=1)
ppn = ppn.fit(X_train1, y_train)
y_pred = ppn.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1889
Accuracy: 0.84
[[5006  994]
 [ 895 5122]]


0.6856971798339929

In [42]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10)
clf = clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1771
Accuracy: 0.85
[[5351  649]
 [1122 4895]]


0.7074782167255571

In [43]:
import sklearn
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
clf = LDA()
clf.fit(X_train1, y_train)
y_pred = clf.predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1909
Accuracy: 0.84
[[4903 1097]
 [ 812 5205]]


0.6830303792813288

In [44]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 2189
Accuracy: 0.82
[[5027  973]
 [1216 4801]]


0.6362233589854126

In [45]:
from sklearn.neural_network import MLPClassifier
gnb = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(13, 2), random_state=1)
y_pred = gnb.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 1510
Accuracy: 0.87
[[5274  726]
 [ 784 5233]]


0.7487271688899237

In [46]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
y_pred = neigh.fit(X_train1, y_train).predict(X_test1)
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))
from sklearn.metrics import matthews_corrcoef
matthews_corrcoef(y_test, y_pred)

Misclassified samples: 667
Accuracy: 0.94
[[5396  604]
 [  63 5954]]


0.8926027197726882